### ISSUE TITLE
Replace argument names of “susceptibility” and “p_susceptibility”

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#119]
Possibly more explicit argument names may help users to relate each of them to the between or within variation:

Here are two proposals:
- `group_susceptibility` ← instead of `susceptibility`, and
- `within_group_susceptibility` ← instead of `p_susceptibility`.

However, these also may be long-name alternatives.

**Comment by pratikunterwegs** [comment]
I'm less sure of this change, as the `p_susceptibility` matrix is (as I understand it), the mapping of demographic groups to susceptibility groups. If there's a standard name for this that can be shortended, happy to replace - but this will be a change that breaks older workflows (if any exist).

**Comment by avallecam** [comment]
True, I just review it again! 

Refrasing, this matrix below contains all in one, the between and within group susceptibility. In this case, the different between-group susceptibilities (under un-immunised) plus one group of a different susceptibility (25% immunization effect) for each age-group: 

```
> susc_immunised
     Un-immunised Immunised
[1,]          0.2     0.150
[2,]          0.5     0.375
[3,]          0.6     0.450
[4,]          0.9     0.675
[5,]          1.0     0.750
```

While this other one below contains the _**proportion**_ of immunized people between and within groups. Here I just made a little change (`0.4` instead of `0.5`) to see some variability:

```
immunisation_rate <- rep(0.4, n_demo_groups)
> p_susc_immunised
         immunised
[1,] 0.6       0.4
[2,] 0.6       0.4
[3,] 0.6       0.4
[4,] 0.6       0.4
[5,] 0.6       0.4
```

This is why
- the first one is called the _demography-susceptibility matrix_ as a whole in `susceptibility` and 
- the second one is the _**proportion**_ of population that belongs to each group of the _demography-susceptibility matrix_ in `p_susceptibility` (with a sum of `1.0` per row)

If my reasoning above is correct, then an extended scenario could include a third group of immune-suppressed population in this way:

```
susceptibility
     Immune-suppressed Un-immunised Immunised
[1,]                 1          0.2     0.150
[2,]                 1          0.5     0.375
[3,]                 1          0.6     0.450
[4,]                 1          0.9     0.675
[5,]                 1          1.0     0.750

p_susceptibility
     immunesupressed unimmunised immunised
[1,]             0.1         0.5       0.4
[2,]             0.1         0.5       0.4
[3,]             0.1         0.5       0.4
[4,]             0.1         0.5       0.4
[5,]             0.1         0.5       0.4
```

**Comment by pratikunterwegs** [comment]
Yes, this is basically it. A more complete model formulation could/should also separate the contact matrix by susceptibility status for very susceptible groups to reflect their social/healthcare situation (see also comments in PR #121).

**Comment by avallecam** [comment]
Thanks for the clarification!
