### ISSUE TITLE
Replace the text line in code chunk about immunisation rate

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#129]
About this line:
https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/varying_susceptibility.Rmd#L256-L257

Please, confirm if the line 256 corresponds to case 4 in #128 

If it is, then line 256 should say sth like:
```
# immunisation rate is 50% in all age groups
immunisation_rate <- rep(0.5, n_demo_grps)
```

**Comment by pratikunterwegs** [comment]
Already fixed in #121 via 74fc29b4000649627a5f82cb0ce9629d14a2d8b8
