### ISSUE TITLE
Add reference links to sources of heterogeneous susceptibility

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#130]
This vignette could be a good place to add references to these. They can inform users where to gather this information for their own purposes.

For example, here in the intro paragraph:

https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/varying_susceptibility.Rmd#L19

We can add the following:

"_(...) Such heterogeneity may be age-dependent and vary between age groups_ due to [age-related impaired or dysregulated host immunity](https://www.jci.org/articles/view/144115). The information for this can be gathered from stratified attack rates or prevalence estimates from pathogens with similar immune responses (like SARS, MERS, and COVID-19).

"For between-group differences, users may prefer to gather this information from stratified [prevalence estimates](https://www.nature.com/articles/s41467-021-21237-w/tables/2) over [observed incidence case rate](https://coronavirus.data.gov.uk/details/cases?areaType=nation%26areaName=England#card-case_rates_by_age_and_sex) due to [surveillance bias](https://www.bmj.com/content/374/bmj.n2126) towards registering more symptomatic individuals.

"These patterns may also be context depended because different patterns were observed for the same disease in different countries. For example, after the first peak of COVID-19 cases, [in Peru](https://www.thelancet.com/action/showFullTableHTML?isHtml=true&tableId=tbl0001&pii=S2589-5370%2821%2900081-X) prevalence by age groups had a uniform distribution, while [in the UK](https://www.nature.com/articles/s41467-021-21237-w/tables/2) it had a heterogeneous one."

-----------------

Also here:

https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/varying_susceptibility.Rmd#L253

We can add the following:

"For within-group differences, users may gather this information from [vaccination percentage uptake](https://coronavirus.data.gov.uk/details/vaccinations?areaType=nation%26areaName=England#card-vaccination_uptake_by_vaccination_date_age_demographics) within age groups, or alternatively, the [percentage of vaccinated people](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/articles/coronaviruscovid19latestinsights/vaccines) in last months in case of known [antibody response decays](https://www.science.org/doi/full/10.1126/sciimmunol.abe0367)."

**Comment by pratikunterwegs** [comment]
I've added a new section 'Primer on heterogeneous susceptibility' in the main body of the vignette. This keeps the structure of the vignettes as > Opening paragraph > Redirection to earlier vignettes > Use case > Assumptions > Main body.

The main body text is

> _Susceptibility to infection may be age-dependent and vary between demographic groups_, for example, between age groups due to [age-related impaired or dysregulated host immunity](https://www.jci.org/articles/view/144115).
> Susceptibility to infection in different demographic groups may be estimated from stratified attack rates or prevalence estimates from pathogens with similar immune responses (such as SARS, MERS, and Covid-19).
> 
> For between-group differences, users may prefer to gather this information from stratified [prevalence estimates](https://www.nature.com/articles/s41467-021-21237-w/tables/2) over [observed incidence case rate](https://coronavirus.data.gov.uk/details/cases?areaType=nation%26areaName=England#card-case_rates_by_age_and_sex) due to [surveillance bias](https://www.bmj.com/content/374/bmj.n2126) towards registering more symptomatic individuals.
> 
> Patterns of heterogeneous susceptibility may also be context dependent, and different patterns may be observed for the same infectious pathogen in different countries.
> For example, after the first peak of Covid-19 cases in 2020, [in Peru](https://www.thelancet.com/action/showFullTableHTML?isHtml=true&tableId=tbl0001&pii=S2589-5370%2821%2900081-X) prevalence had a uniform distribution across age groups, while [in the UK](https://www.nature.com/articles/s41467-021-21237-w/tables/2) prevalence across age groups was heterogeneous.

Later, I've added an information box which will appear in grey.

> ### Getting data on within-group susceptibility differences
> 
> For within-group differences in susceptibility, such as due to immunisation, users could obtain this information from [age-specific vaccination uptake statistics from national governments (here, the UK)](https://coronavirus.data.gov.uk/details/vaccinations?areaType=nation%26areaName=England#card-vaccination_uptake_by_vaccination_date_age_demographics).
> When [antibody response decays](https://www.science.org/doi/full/10.1126/sciimmunol.abe0367) are known for an immunisation course, more detailed statistics on the [percentage of people vaccinated (here, in the UK)](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/articles/coronaviruscovid19latestinsights/vaccines) in the preceding few months only, may be more informative.

I'm a little wary of linking to Covid dashboards, as these could be taken offline in the near future (as the CMMID dashboards have been) - is the coronavirus.data.gov.uk site likely to be maintained in the long term?

**Comment by avallecam** [comment]
Updated suggestion here https://github.com/epiverse-trace/finalsize/pull/121#discussion_r1080559728

**Comment by avallecam** [comment]
I agree with your concern about Covid dashboards. I do not have a paper in mind with similar information, I can work on it. 

For now, Is a [figure from a BBC news report](https://ichef.bbci.co.uk/news/976/cpsprodpb/1342A/production/_123509887_optimised-uk_vax_by_age_4mar-nc.png.webp) more stable than a dashboard? ref: https://www.bbc.co.uk/news/health-55274833

**Comment by pratikunterwegs** [comment]
Let's stick with the dashboard for now, I'm sure we'll find out when they're taken offline - we would know sooner than most anyone else after all.
