### ISSUE TITLE
Imaginary numbers when obtaining eigenvalues and eigen-vectors

### ISSUE THREAD

**Issue by erees** [epiverse-trace/finalsize#131]
*Bugs* may include behaviour that does not impact package functionality, but which seems as though it might not be intended by the package developers.
  
Please place an "x" in all the boxes that apply
---------------------------------------------
  
- [ x] I have the most recent version of finalsize and R
- [ x] I have found a bug
- [ ] I have a [reproducible example](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
- [ ] I want to request a new feature

--------
  
Please include a brief description of the problem with a code example:

I have been using final size with contact data from Dominican Republic. I ran into issues when obtaining eigenvalues and eigen-vectors which returned imaginary numbers. I think extracting the real component will fix this issue (i.e. `max(Re(eigen(matrix_home)$value))`), as it gives the same answers as simulating over mutliple generations.

---------

**Comment by pratikunterwegs** [comment]
Hi @erees thanks for bringing this up. Will fix in a bit, but it might take a small while to push the update to CRAN.

**Comment by pratikunterwegs** [comment]
Thank you @erees for raising this, has been fixed in the most recent PR to main. Do please flag any other issues you encounter as well.
