### ISSUE TITLE
Remove configuration lines of ggplot2 visualizations

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#134]
These are aesthetic suggestions to get plots in fewer steps.

In vignette `finalsize.Rmd`:

- Remove the manually defined `fill = "lightgrey"` and `col = "black"` arguments in geom_col()
- Remove the `coord_cartesian(expand = FALSE)` function in ggplot2 
https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/finalsize.Rmd#L203-L222
https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/finalsize.Rmd#L255-L276

![image](https://user-images.githubusercontent.com/21230390/213888269-0c7bfd97-da7c-4f72-9899-c172171bf45e.png)

In vignette `varying_susceptibility.Rmd`
- Replace the first letter with Upper cases in the `"heterogeneous"` and `"uniform"` scenario columns
- Remove the `theme()` and `coord_cartesian(expand = FALSE)` functions in ggplot2 
- Remove the manually defined `col = "black"` argument in `geom_col()`
- Remove the manually defined `palette = "Cold"` argument in `scale_fill_discrete_qualitative()`

At the end is the final code of the suggestion.

https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/varying_susceptibility.Rmd#L155-L156
https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/varying_susceptibility.Rmd#L174-L208

Here is the final code of the suggestion:

```
# assign scenario name and join data
final_size_heterog$scenario <- "Heterogeneous"
final_size_uniform$scenario <- "Uniform"
```

```
ggplot(final_size_data) +
  geom_col(
    aes(
      x = demo_grp, y = p_infected,
      fill = scenario
    ),
    position = position_dodge(
      width = 0.75
    )
  ) +
  scale_fill_discrete_qualitative(
    name = "Population\nsusceptibility"
  ) +
  scale_y_continuous(
    labels = scales::percent,
    limits = c(0, 1)
  ) +
  theme_classic() +
  labs(
    x = "Age group",
    y = "% Infected"
  )
```
![image](https://user-images.githubusercontent.com/21230390/213888130-d87248cf-101f-4e21-b558-f00d43aa9cb3.png)

**Comment by avallecam** [comment]
The following suggestion also applies to `uncertainty_params.Rmd`:
- Remove the `theme()` and `coord_cartesian(expand = FALSE)` functions in ggplot2

Here: 
https://github.com/epiverse-trace/finalsize/blob/f0ac4127e54579754d08ee92754203f99c0f6ee9/vignettes/uncertainty_params.Rmd#L175-L184

**Comment by pratikunterwegs** [comment]
No, I think good visualisations are important, even if it takes more lines to achieve them. This code is available to users who want to modify it, and has, imo, decent output for those who simply want to copy it.
