### ISSUE TITLE
Replace links in contributing page

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#145]
Some links in the [contributing page](https://epiverse-trace.github.io/finalsize/CONTRIBUTING.html) have dead ends:

- bug reports --> could redirect to [specific issue](https://github.com/epiverse-trace/finalsize/issues/new?assignees=&labels=&template=bug_report.md&title=) or [choose site](https://github.com/epiverse-trace/finalsize/issues/new/choose)
- feature request --> could redirect to [specific issue](https://github.com/epiverse-trace/finalsize/issues/new?assignees=&labels=&template=feature_request.md&title=) or [choose site](https://github.com/epiverse-trace/finalsize/issues/new/choose)
- pull request template --> could redirect to [PR template](https://github.com/epiverse-trace/finalsize/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)

However, this behaviour is also present in the [`epiparameter` package contributing page](https://epiverse-trace.github.io/epiparameter/CONTRIBUTING.html)

So, Is this something that should be solved in the [`packagetemplate`](https://github.com/epiverse-trace/packagetemplate/)?

**Comment by pratikunterwegs** [comment]
Flagging this for @joshwlambert's attention as well since {epiparameter} reportedly has the same issue.
