### ISSUE TITLE
Add contributor details

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/finalsize#160]
This issue is to request that all contributors add their personal details to the DESCRIPTION under the appropriate heading, in a pull request.

I would suggest:
1. All code or documentation contributors please add themselves as "aut" - @avallecam could you please add yourself as an author as you've written one vignette and one vignette section.
2. Could all reviewers please add themselves as "rev" - @joshwlambert you might wish to add yourself for your many reviews.

**Comment by joshwlambert** [comment]
@pratikunterwegs Thanks for raising. I'm personally fine with not being added to the DESCRIPTION file for reviewing. 

This would be a good topic for the Epiverse-TRACE RSE meeting agenda, to see what others think about reviewers as contributors.

**Comment by pratikunterwegs** [comment]
Thanks @joshwlambert, I'll take the Epinowcast line and say that all contributions should be recognised and reviewing is an important part of development, but feel free to opt out. I've added this issue to the RSE meeting agenda.
