### ISSUE TITLE
rename the r0_to_lambda() function title

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/finalsize#168]
It should be `Calculate transmission rate (\eqn{\lambda}) from \eqn{R_0}`

https://github.com/epiverse-trace/finalsize/blob/e75e1a65338d633fa8cc7ee6567fd120595390d4/R/r0_conversions.R#L111-L115

**Comment by pratikunterwegs** [comment]
Thanks, already tagged by @Bisaloo in the full review #161 and fixed in commit https://github.com/epiverse-trace/finalsize/pull/161/commits/d1d0655ff0f340049672ca98e500c5f8c58db599
