### ISSUE TITLE
Create functions to convert between R0 and transmissibility

### ISSUE THREAD

**Issue by BlackEdder** [epiverse-trace/finalsize#27]
There are use cases for using both R0 and transmissibiltiy, so it would be good to have functions to convert between these.

In fluevidencesynthesis it was done: https://github.com/MJomaba/flu-evidence-synthesis/blob/c5cbd127ff717f3637c5ed298dd3428e0fa6b05d/src/rapi.cc#L740-L787

This approach should only need minor changes for our needs.

**Comment by pratikunterwegs** [comment]
Re-upping this issue after recent dicussion on including R<sub>0</sub> and transmissibility in `final_size`.

**Comment by pratikunterwegs** [comment]
Hi @BlackEdder just pinging to check whether this is still something that would be useful to implement? Could be done pretty quickly and added to #152.

**Comment by BlackEdder** [comment]
I think this would still be nice to do, especially if it is not too much effort.

**Comment by pratikunterwegs** [comment]
Will add to #152 later this week then.
