### ISSUE TITLE
Discrepency between R and C implementations

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/finalsize#69]
Assuming the c++ implementation is correct then https://github.com/epiverse-trace/finalsize/blob/41ef432ddfbff511dfbad8f15da43f2566b4e607/R/iterative_solver.R#L41
and https://github.com/epiverse-trace/finalsize/blob/41ef432ddfbff511dfbad8f15da43f2566b4e607/R/newton_solver.R#L35 should be changed to 
```
contact_matrix_ <- contact_matrix * susceptibility %o% demography_vector
```
or the micro optimized 
```
contact_matrix_ <- contact_matrix * tcrossprod(susceptibility, demography_vector)
```
If/when the suggestion in #68 is taken up this will only need correcting in one place.
Tests that compare the c++ and R results to desired tolerance should be sufficient to test this.

**Comment by Bisaloo** [comment]
Related: #7
