### ISSUE TITLE
Offer a way to pass different p_susceptibility without having to recompute everything

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/finalsize#72]
The multiplication by `p_susceptibility` happens at the end of the `final_size()` call, after the solver call.

Yet, if users pass different `p_susceptibility` values, they will have to go through the slow solving step again.

Is there a way to allow passing multiple `p_susceptibility` values in a single function call, without making the interface too complicated?

**Comment by pratikunterwegs** [comment]
I think so - on the branch `feature/single_func`, it would require:
1. Changes to `epi_spread` and the overall calling function `final_size_`. 
2. Changes to the argument `p_susceptibility` to allow either a single matrix, or a (named?) list of matrices representing different demography-susceptibility distributions.
3. Changing the return type for the overall function `final_size` which is either a vector or (named?) list.
This all seems do-able, and can be included in the upcoming PR #73.

**Comment by pratikunterwegs** [comment]
Hi @Bisaloo, thanks for this suggestion. After taking a deeper look, I've found that `p_susceptibility` is used to scale the demography vector within `epi_spread`, and this scaled demography vector is passed to the solvers (and later used to scale the contact matrix).

https://github.com/epiverse-trace/finalsize/blob/c1149dc7cd22c42961c62410d7b752111962d516/src/epi_spread.h#L31-L40

If I understand correctly this means that a new `p_susceptibility` matrix requires a new solver run. I'm trying to think of another strategy to achieve the functionality we are considering (multiple `p_susceptibility` for a single solver call), but haven't got one yet. If you agree with this assessment, I'll close the issue.

**Comment by Bisaloo** [comment]
You're right, I missed this. Feel free to close this issue.
