### ISSUE TITLE
Add an issue template for finalsize

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/finalsize#83]
`finalsize` does not have a predefined template for opening issues that report bugs or other unintended behaviour. Adding this would help users report these in a way that is easy for developers to parse more quickly for the key problems.

**Comment by Bisaloo** [comment]
Note that in the future, this will likely be deprecated in favour of https://github.com/epiverse-trace/.github/issues/1.

**Comment by pratikunterwegs** [comment]
Thanks for pointing that out. Is that likely to be soon? I see it has been open a while, so I would propose to add the templates for each repo for now and (manually?) point users to the org-wide template once it is ready (GH already does so for the contributor document so I assume it will do this for the issues as well).

**Comment by Bisaloo** [comment]
Not sure about the exact timeline so feel free to add a template here for now. I just wanted to point it out now to keep you in the loop.

Once this is added in the `.github` repo, it will automatically be used in all organisation repos that don't overwrite it: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file.

**Comment by Bisaloo** [comment]
Yes, exactly, the idea is that repos that need it can overwrite the defaults but for others, it gives us a single place to update instead of having to update every individual repo.
