### ISSUE TITLE
Release finalsize 0.1.0

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/finalsize#96]
First release:

* [x] #101
* [x] #102
* [x] #103
* [x] Check that all exported functions have `@return` and `@examples`
* [x] #104
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] #105

Prepare for release:

* [x] `git pull`
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)` (#97)
* [x] `devtools::check_win_devel()`: https://win-builder.r-project.org/7z4p6Xvm5Cm1/
* [x] `rhub::check_for_cran()` :
  - Windows: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-4bf5fc342efd40a38515f5d98596023e
  - Ubuntu: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-8592939ae200414b82647cbad9e44354
  - Fedora: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-3ecf01f9c0894341a71be9b24d796b64
  - Debian: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-0222883110ab49709452684e755b677e
* [x] `rhub::check(platform = 'ubuntu-rchk')`: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-040b5a3c0d5240dc908e68c3b8ae135c, to be considered a pass based on https://github.com/kalibera/rchk/issues/22#issuecomment-656036156?
* [x] `rhub::check_with_sanitizers()`: https://builder.r-hub.io/status/finalsize_0.1.tar.gz-e382c002a36d4399a1cd2afd08dceb60
* [x] `git push`
* ~~Draft blog post~~

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `usethis::use_news_md()`
* [x] `git push`
* ~~Finish blog post~~
* [x] Tweet
* ~~Add link to blog post in pkgdown news menu~~

**Comment by Bisaloo** [comment]
One last thing I don't see here:

- [ ] Add github & pkgdown links in `DESCRIPTION`. Example:

https://github.com/tidyverse/ggplot2/blob/4fea51b1eb2cdacebeacf425627dcbc1d61a5d3e/DESCRIPTION#L28-L29

This makes it easier to discover the GitHub repo & the pkgdown documentation and it enables cross-linking from other pkgdown websites.

**Comment by pratikunterwegs** [comment]
I have not run `usethis::use_version("minor")`, as the version in DESCRIPTION is already 0.1.0, which is what we want to achieve if I understand correctly.

**Comment by pratikunterwegs** [comment]
I haven't marked the tasks `rhub::check_for_cran()` and `rhub::check_with_sanitizers()` as done, as I don't know whether the notes I'm getting (and the Fedora build failure) are likely to meet requirements.

Still, in the absence of better fixes for these persistent issues, I am submitting to CRAN now.

**Comment by pratikunterwegs** [comment]
I have marked the `rhub` checks as completed, as `finalsize` has now been accepted on CRAN: https://cran.r-project.org/package=finalsize.

Further steps also appear to be completed:
1. Releasing `finalsize` v0.1 on Github,
2. Adding a changelog (NEWS.md),
3. Incrementing the Github version to v0.1.0.9000.

I am marking the 'Tweet' task as provisionally done; tagging @annacarnegie and @avallecam on the community engagement side for this.

Please close this issue as fixed when convenient.
