### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/finalsize#99]
While working on #94, I noticed a lot of redundancy in the tests. Each time the code changes somewhere, you have to update tests in many locations that check essentially the same thing.

I understand this comes from the sinuous development process this package went through but it would probably be valuable at some point to refactor & simplify the test structure to facilitate future update.

**Comment by pratikunterwegs** [comment]
Agreed, can do some test rationalisation over the next few days.
